FROM node:22-alpine
WORKDIR /usr/src/app
# Copy the package-lock and package jsons to the working dir
COPY package*.json ./
# Install dependencies for the Bot
RUN npm install --production axios dotenv node-schedule
# Copy the rest of the application code to the working directory
COPY index.v0.js .
# Run the bot
CMD [ "node", "index.js" ]