services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - API_BASE=${API_BASE}
      - API_VERSION=${API_VERSION}
      - ENDPOINT=${ENDPOINT}
      - CURRENCY_PAIRS=${CURRENCY_PAIRS}
      - ALERT_THRESHOLD=${ALERT_THRESHOLD}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
